name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and Setup Node.js
        uses: actions/checkout@v3
        with:
          node-version: 16

      - name: Install dependencies and Run tests (if applicable)
        run: |
          npm ci
          # Uncomment the line below if you have tests
          # npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code and Setup Node.js
        uses: actions/checkout@v3
        with:
          node-version: 16

      - name: Install dependencies and Build
        run: |
          npm ci
          CI= npm run build

      - name: Deploy
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/JacobThacker/CryptoSoc.git
          npm run deploy
